// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccessToken = "access_token"

// AccessToken mapped from table <access_token>
type AccessToken struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID     int64  `gorm:"column:uid;not null;comment:用户 id" json:"uid"`             // 用户 id
	Stoken  string `gorm:"column:stoken;not null;comment:accesstoken" json:"stoken"` // accesstoken
	Expires int64  `gorm:"column:expires;not null;comment:到期时间戳" json:"expires"`     // 到期时间戳
	Ctime   *int64 `gorm:"column:ctime" json:"ctime"`
}

// TableName AccessToken's table name
func (*AccessToken) TableName() string {
	return TableNameAccessToken
}
