// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID       int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Phone    string  `gorm:"column:phone;not null;comment:手机号" json:"phone"`    // 手机号
	Credit   *int32  `gorm:"column:credit;default:30;comment:积分" json:"credit"` // 积分
	Operator *string `gorm:"column:operator;comment:运营商" json:"operator"`       // 运营商
	Ctime    *int64  `gorm:"column:ctime;comment:创建时间" json:"ctime"`            // 创建时间
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
