// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fiber-boot/internal/app"
	"fiber-boot/internal/core"
	"fiber-boot/internal/dao"
	"fiber-boot/internal/module/account"
)

// Injectors from wire.go:

func InitApp() *app.App {
	config := core.NewConfig()
	db := core.NewDB(config)
	accountDAO := dao.NewAccountDAO(db)
	accessTokenDAO := dao.NewAccessTokenDAO(db)
	accountHandler := account.NewAccountHandler(accountDAO, accessTokenDAO)
	server := app.NewServer(config, accountHandler, accessTokenDAO)
	appApp := app.NewApp(server)
	return appApp
}
